#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define HORIZONTAL_VIEW_OFFSET 2
#define VERTICAL_VIEW_OFFSET 2
#define FPS_SAMPLE_SIZE 20
#define TABS_VIEW_SIZE 4
#define CURSOR_VIEW_SIZE 3
#define LINE_NUMBER_SPACE 4
#define TEXT_COLOR \
    (SDL_Color) { 255, 255, 255, 255 }
#define LINE_TEXT_COLOR \
    (SDL_Color) { 200, 200, 200, 255 }
#define EMPTY_LINE_SELECTED_VIEW_WIDTH 0.2

#define DEFAULT_WIDTH 1100
#define DEFAULT_HEIGHT 800

#endif
